log_root: /opt/omnia/logs
pxe_mapping_file_path: "/opt/omnia/input/project_default/pxe_mapping_file.csv"
k8s_master_log_dirs:
  - /var/log/containers/
  - /var/log/pods/
  - /var/log/calico/
k8s_master_log_files:
  - /var/log/cloud-init.log
  - /var/log/cloud-init-output.log
k8s_worker_log_files:
  - /var/log/cloud-init.log
  - /var/log/cloud-init-output.log
slurm_ctl_log_dirs:
  - /var/log/slurm/
slurm_ctl_log_files:
  - /var/log/cloud-init.log
  - /var/log/cloud-init-output.log
  - /var/log/ldms-cloudinit.log
slurm_node_log_dirs:
  - /var/log/slurm/
slurm_node_log_files:
  - /var/log/cloud-init.log
  - /var/log/cloud-init-output.log
